<?php

namespace App\Domains\FlatOrder\Http\Controllers\Api\Flatorder;

use App\Http\Controllers\Controller;
use App\Domains\FlatOrder\Models\Flatorder;
use Illuminate\Http\Request;

/**
 * Class FlatorderController.
 */
class FlatorderController extends Controller
{
    /**
     * @OA\Get(
     * path="/api/flatorder",
     * summary="Get All Flatorders",
     * description="Show All Flatorders",
     * operationId="getAllFlatorders",
     * tags={"Flatorder"},
     * @OA\Response(
     *    response=200,
     *    description="Returns when Flatorder are found",
     *    @OA\JsonContent(
     *     @OA\Items(
     *       @OA\Property(property="id", type="Integer", example="1"),
     *       @OA\Property(property="order_number", type="text", example="1"),
     *       @OA\Property(property="waybill", type="text", example="1"),
     *       @OA\Property(property="parent_id", type="Integer", example="1"),
     *       @OA\Property(property="order_id", type="Integer", example="1"),
     *       @OA\Property(property="order_details_id", type="Integer", example="1"),
     *       @OA\Property(property="type_id", type="Integer", example="1"),
     *       @OA\Property(property="rate", type="Integer", example="1"),
     *       @OA\Property(property="status", type="Integer", example="1"),
     *       @OA\Property(property="payment_status", type="Integer", example="1"),
     *       @OA\Property(property="package_status", type="Integer", example="1"),
     *       @OA\Property(property="remaining_balance", type="decimal", example="1"),
     *       @OA\Property(property="price", type="decimal", example="1"),
     *       @OA\Property(property="payment_type_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="collection_amount", type="decimal", example="1"),
     *       @OA\Property(property="collection_type_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="comment_id", type="Integer", example="1"),
     *       @OA\Property(property="important_comment_text", type="text", example="1"),
     *       @OA\Property(property="comments_count", type="Integer", example="1"),
     *       @OA\Property(property="allow_receiver_contact", type="Integer", example="1"),
     *       @OA\Property(property="send_receiver_msg", type="Integer", example="1"),
     *       @OA\Property(property="car_needed", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_wakilni", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_customer", type="Integer", example="1"),
     *       @OA\Property(property="active", type="Integer", example="1"),
     *       @OA\Property(property="is_critical", type="Integer", example="1"),
     *       @OA\Property(property="require_signature", type="Integer", example="1"),
     *       @OA\Property(property="require_picture", type="Integer", example="1"),
     *       @OA\Property(property="same_package", type="Integer", example="1"),
     *       @OA\Property(property="piggy_bank_submission_id", type="Integer", example="1"),
     *       @OA\Property(property="completed_on", type="datetime", example="1"),
     *       @OA\Property(property="status_updated_at", type="datetime", example="1"),
     *       @OA\Property(property="become_critical_date", type="datetime", example="1"),
     *       @OA\Property(property="confirmed_at", type="datetime", example="1"),
     *       @OA\Property(property="note", type="text", example="1"),
     *       @OA\Property(property="preferred_sender_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_sender_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_sender_to_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_receiver_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_to_time", type="time", example="1"),
     *       @OA\Property(property="senderable_id", type="Integer", example="1"),
     *       @OA\Property(property="senderable_type", type="text", example="1"),
     *       @OA\Property(property="senderable_name", type="text", example="1"),
     *       @OA\Property(property="senderable_phone_number", type="text", example="1"),
     *       @OA\Property(property="senderable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_id", type="Integer", example="1"),
     *       @OA\Property(property="receiverable_type", type="text", example="1"),
     *       @OA\Property(property="receiverable_name", type="text", example="1"),
     *       @OA\Property(property="receiverable_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="sender_location_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_location_label", type="text", example="1"),
     *       @OA\Property(property="sender_area_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_area_label", type="text", example="1"),
     *       @OA\Property(property="sender_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_zone_label", type="text", example="1"),
     *       @OA\Property(property="receiver_location_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_location_label", type="text", example="1"),
     *       @OA\Property(property="receiver_area_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_area_label", type="text", example="1"),
     *       @OA\Property(property="receiver_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_zone_label", type="text", example="1"),
     *       @OA\Property(property="task_scheduled_date", type="datetime", example="1"),
     *       @OA\Property(property="task_scheduled_from_time", type="time", example="1"),
     *       @OA\Property(property="task_scheduled_to_time", type="time", example="1"),
     *       @OA\Property(property="task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="packages", type="longtext", example="1"),
     *       @OA\Property(property="customer_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_name", type="text", example="1"),
     *       @OA\Property(property="customer_golden_rule", type="text", example="1"),
     *       @OA\Property(property="customer_is_active", type="Integer", example="1"),
     *       @OA\Property(property="customer_account_manager_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_industry_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_name", type="text", example="1"),
     *       @OA\Property(property="piggy_bank_id", type="Integer", example="1"),
     *       @OA\Property(property="store_id", type="Integer", example="1"),
     *       @OA\Property(property="app_token_id", type="Integer", example="1"),
     *       @OA\Property(property="app_ref_id", type="Integer", example="1"),
     *       @OA\Property(property="fulfillment_id", type="Integer", example="1"),
     *       @OA\Property(property="deleted_at", type="string", example="null"),
     *       @OA\Property(property="created_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *       @OA\Property(property="updated_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *    )
     * )
     * )
     * )
     */
    public function index()
    {
        return Flatorder::all();
    }



    /**
     * @OA\Get(
     * path="/api/flatorder/{id}",
     * summary="Get Flatorder by id",
     * description="Show one Flatorder by id",
     * operationId="getOneFlatorders",
     * tags={"flatorder"},
     * @OA\Parameter(
     *    description="ID of flatorder",
     *    in="path",
     *    name="id",
     *    required=true,
     *    example="1",
     * ),
     * @OA\Response(
     *    response=404,
     *    description="Returns when flatorder id is not found",
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="Resource not found"),
     *    )
     * ),
     * @OA\Response(
     *    response=200,
     *    description="Returns when Flatorder is found",
     *    @OA\JsonContent(
     *       @OA\Property(property="id", type="Integer", example="1"),
     *       @OA\Property(property="order_number", type="text", example="1"),
     *       @OA\Property(property="waybill", type="text", example="1"),
     *       @OA\Property(property="parent_id", type="Integer", example="1"),
     *       @OA\Property(property="order_id", type="Integer", example="1"),
     *       @OA\Property(property="order_details_id", type="Integer", example="1"),
     *       @OA\Property(property="type_id", type="Integer", example="1"),
     *       @OA\Property(property="rate", type="Integer", example="1"),
     *       @OA\Property(property="status", type="Integer", example="1"),
     *       @OA\Property(property="payment_status", type="Integer", example="1"),
     *       @OA\Property(property="package_status", type="Integer", example="1"),
     *       @OA\Property(property="remaining_balance", type="decimal", example="1"),
     *       @OA\Property(property="price", type="decimal", example="1"),
     *       @OA\Property(property="payment_type_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="collection_amount", type="decimal", example="1"),
     *       @OA\Property(property="collection_type_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="comment_id", type="Integer", example="1"),
     *       @OA\Property(property="important_comment_text", type="text", example="1"),
     *       @OA\Property(property="comments_count", type="Integer", example="1"),
     *       @OA\Property(property="allow_receiver_contact", type="Integer", example="1"),
     *       @OA\Property(property="send_receiver_msg", type="Integer", example="1"),
     *       @OA\Property(property="car_needed", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_wakilni", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_customer", type="Integer", example="1"),
     *       @OA\Property(property="active", type="Integer", example="1"),
     *       @OA\Property(property="is_critical", type="Integer", example="1"),
     *       @OA\Property(property="require_signature", type="Integer", example="1"),
     *       @OA\Property(property="require_picture", type="Integer", example="1"),
     *       @OA\Property(property="same_package", type="Integer", example="1"),
     *       @OA\Property(property="piggy_bank_submission_id", type="Integer", example="1"),
     *       @OA\Property(property="completed_on", type="datetime", example="1"),
     *       @OA\Property(property="status_updated_at", type="datetime", example="1"),
     *       @OA\Property(property="become_critical_date", type="datetime", example="1"),
     *       @OA\Property(property="confirmed_at", type="datetime", example="1"),
     *       @OA\Property(property="note", type="text", example="1"),
     *       @OA\Property(property="preferred_sender_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_sender_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_sender_to_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_receiver_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_to_time", type="time", example="1"),
     *       @OA\Property(property="senderable_id", type="Integer", example="1"),
     *       @OA\Property(property="senderable_type", type="text", example="1"),
     *       @OA\Property(property="senderable_name", type="text", example="1"),
     *       @OA\Property(property="senderable_phone_number", type="text", example="1"),
     *       @OA\Property(property="senderable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_id", type="Integer", example="1"),
     *       @OA\Property(property="receiverable_type", type="text", example="1"),
     *       @OA\Property(property="receiverable_name", type="text", example="1"),
     *       @OA\Property(property="receiverable_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="sender_location_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_location_label", type="text", example="1"),
     *       @OA\Property(property="sender_area_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_area_label", type="text", example="1"),
     *       @OA\Property(property="sender_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_zone_label", type="text", example="1"),
     *       @OA\Property(property="receiver_location_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_location_label", type="text", example="1"),
     *       @OA\Property(property="receiver_area_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_area_label", type="text", example="1"),
     *       @OA\Property(property="receiver_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_zone_label", type="text", example="1"),
     *       @OA\Property(property="task_scheduled_date", type="datetime", example="1"),
     *       @OA\Property(property="task_scheduled_from_time", type="time", example="1"),
     *       @OA\Property(property="task_scheduled_to_time", type="time", example="1"),
     *       @OA\Property(property="task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="packages", type="longtext", example="1"),
     *       @OA\Property(property="customer_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_name", type="text", example="1"),
     *       @OA\Property(property="customer_golden_rule", type="text", example="1"),
     *       @OA\Property(property="customer_is_active", type="Integer", example="1"),
     *       @OA\Property(property="customer_account_manager_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_industry_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_name", type="text", example="1"),
     *       @OA\Property(property="piggy_bank_id", type="Integer", example="1"),
     *       @OA\Property(property="store_id", type="Integer", example="1"),
     *       @OA\Property(property="app_token_id", type="Integer", example="1"),
     *       @OA\Property(property="app_ref_id", type="Integer", example="1"),
     *       @OA\Property(property="fulfillment_id", type="Integer", example="1"),
     *       @OA\Property(property="deleted_at", type="string", example="null"),
     *       @OA\Property(property="created_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *       @OA\Property(property="updated_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *    )
     * )
     * )
     * )
     */
    public function show(Flatorder $flatorder)
    {
        return $flatorder;
    }

    /**
     * @OA\Post (
     * path="/api/flatorder",
     * summary="Create New Flatorder",
     * description="Create One Flatorder",
     * operationId="postOneFlatorders",
     * tags={"flatorder"},
     * @OA\RequestBody(
     *    required=true,
     *    description="Flatorder fields",
     *    @OA\JsonContent(
     *       required={"name"},
     *       @OA\Property(property="id", type="Integer", example="1"),
     *       @OA\Property(property="order_number", type="text", example="1"),
     *       @OA\Property(property="waybill", type="text", example="1"),
     *       @OA\Property(property="parent_id", type="Integer", example="1"),
     *       @OA\Property(property="order_id", type="Integer", example="1"),
     *       @OA\Property(property="order_details_id", type="Integer", example="1"),
     *       @OA\Property(property="type_id", type="Integer", example="1"),
     *       @OA\Property(property="rate", type="Integer", example="1"),
     *       @OA\Property(property="status", type="Integer", example="1"),
     *       @OA\Property(property="payment_status", type="Integer", example="1"),
     *       @OA\Property(property="package_status", type="Integer", example="1"),
     *       @OA\Property(property="remaining_balance", type="decimal", example="1"),
     *       @OA\Property(property="price", type="decimal", example="1"),
     *       @OA\Property(property="payment_type_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="collection_amount", type="decimal", example="1"),
     *       @OA\Property(property="collection_type_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="comment_id", type="Integer", example="1"),
     *       @OA\Property(property="important_comment_text", type="text", example="1"),
     *       @OA\Property(property="comments_count", type="Integer", example="1"),
     *       @OA\Property(property="allow_receiver_contact", type="Integer", example="1"),
     *       @OA\Property(property="send_receiver_msg", type="Integer", example="1"),
     *       @OA\Property(property="car_needed", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_wakilni", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_customer", type="Integer", example="1"),
     *       @OA\Property(property="active", type="Integer", example="1"),
     *       @OA\Property(property="is_critical", type="Integer", example="1"),
     *       @OA\Property(property="require_signature", type="Integer", example="1"),
     *       @OA\Property(property="require_picture", type="Integer", example="1"),
     *       @OA\Property(property="same_package", type="Integer", example="1"),
     *       @OA\Property(property="piggy_bank_submission_id", type="Integer", example="1"),
     *       @OA\Property(property="completed_on", type="datetime", example="1"),
     *       @OA\Property(property="status_updated_at", type="datetime", example="1"),
     *       @OA\Property(property="become_critical_date", type="datetime", example="1"),
     *       @OA\Property(property="confirmed_at", type="datetime", example="1"),
     *       @OA\Property(property="note", type="text", example="1"),
     *       @OA\Property(property="preferred_sender_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_sender_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_sender_to_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_receiver_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_to_time", type="time", example="1"),
     *       @OA\Property(property="senderable_id", type="Integer", example="1"),
     *       @OA\Property(property="senderable_type", type="text", example="1"),
     *       @OA\Property(property="senderable_name", type="text", example="1"),
     *       @OA\Property(property="senderable_phone_number", type="text", example="1"),
     *       @OA\Property(property="senderable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_id", type="Integer", example="1"),
     *       @OA\Property(property="receiverable_type", type="text", example="1"),
     *       @OA\Property(property="receiverable_name", type="text", example="1"),
     *       @OA\Property(property="receiverable_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="sender_location_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_location_label", type="text", example="1"),
     *       @OA\Property(property="sender_area_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_area_label", type="text", example="1"),
     *       @OA\Property(property="sender_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_zone_label", type="text", example="1"),
     *       @OA\Property(property="receiver_location_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_location_label", type="text", example="1"),
     *       @OA\Property(property="receiver_area_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_area_label", type="text", example="1"),
     *       @OA\Property(property="receiver_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_zone_label", type="text", example="1"),
     *       @OA\Property(property="task_scheduled_date", type="datetime", example="1"),
     *       @OA\Property(property="task_scheduled_from_time", type="time", example="1"),
     *       @OA\Property(property="task_scheduled_to_time", type="time", example="1"),
     *       @OA\Property(property="task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="packages", type="longtext", example="1"),
     *       @OA\Property(property="customer_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_name", type="text", example="1"),
     *       @OA\Property(property="customer_golden_rule", type="text", example="1"),
     *       @OA\Property(property="customer_is_active", type="Integer", example="1"),
     *       @OA\Property(property="customer_account_manager_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_industry_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_name", type="text", example="1"),
     *       @OA\Property(property="piggy_bank_id", type="Integer", example="1"),
     *       @OA\Property(property="store_id", type="Integer", example="1"),
     *       @OA\Property(property="app_token_id", type="Integer", example="1"),
     *       @OA\Property(property="app_ref_id", type="Integer", example="1"),
     *       @OA\Property(property="fulfillment_id", type="Integer", example="1"),
     *    ),
     * ),
     * @OA\Response(
     *    response=401,
     *    description="Returns when name or description deos'nt o the RequestBody ",
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="name and description field are required"),
     *    )
     * ),
     * @OA\Response(
     *    response=200,
     *    description="Returns when Flatorder has been created",
     *    @OA\JsonContent(
     *     @OA\Items(
     *       @OA\Property(property="id", type="Integer", example="1"),
     *       @OA\Property(property="order_number", type="text", example="1"),
     *       @OA\Property(property="waybill", type="text", example="1"),
     *       @OA\Property(property="parent_id", type="Integer", example="1"),
     *       @OA\Property(property="order_id", type="Integer", example="1"),
     *       @OA\Property(property="order_details_id", type="Integer", example="1"),
     *       @OA\Property(property="type_id", type="Integer", example="1"),
     *       @OA\Property(property="rate", type="Integer", example="1"),
     *       @OA\Property(property="status", type="Integer", example="1"),
     *       @OA\Property(property="payment_status", type="Integer", example="1"),
     *       @OA\Property(property="package_status", type="Integer", example="1"),
     *       @OA\Property(property="remaining_balance", type="decimal", example="1"),
     *       @OA\Property(property="price", type="decimal", example="1"),
     *       @OA\Property(property="payment_type_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="collection_amount", type="decimal", example="1"),
     *       @OA\Property(property="collection_type_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="comment_id", type="Integer", example="1"),
     *       @OA\Property(property="important_comment_text", type="text", example="1"),
     *       @OA\Property(property="comments_count", type="Integer", example="1"),
     *       @OA\Property(property="allow_receiver_contact", type="Integer", example="1"),
     *       @OA\Property(property="send_receiver_msg", type="Integer", example="1"),
     *       @OA\Property(property="car_needed", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_wakilni", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_customer", type="Integer", example="1"),
     *       @OA\Property(property="active", type="Integer", example="1"),
     *       @OA\Property(property="is_critical", type="Integer", example="1"),
     *       @OA\Property(property="require_signature", type="Integer", example="1"),
     *       @OA\Property(property="require_picture", type="Integer", example="1"),
     *       @OA\Property(property="same_package", type="Integer", example="1"),
     *       @OA\Property(property="piggy_bank_submission_id", type="Integer", example="1"),
     *       @OA\Property(property="completed_on", type="datetime", example="1"),
     *       @OA\Property(property="status_updated_at", type="datetime", example="1"),
     *       @OA\Property(property="become_critical_date", type="datetime", example="1"),
     *       @OA\Property(property="confirmed_at", type="datetime", example="1"),
     *       @OA\Property(property="note", type="text", example="1"),
     *       @OA\Property(property="preferred_sender_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_sender_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_sender_to_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_receiver_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_to_time", type="time", example="1"),
     *       @OA\Property(property="senderable_id", type="Integer", example="1"),
     *       @OA\Property(property="senderable_type", type="text", example="1"),
     *       @OA\Property(property="senderable_name", type="text", example="1"),
     *       @OA\Property(property="senderable_phone_number", type="text", example="1"),
     *       @OA\Property(property="senderable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_id", type="Integer", example="1"),
     *       @OA\Property(property="receiverable_type", type="text", example="1"),
     *       @OA\Property(property="receiverable_name", type="text", example="1"),
     *       @OA\Property(property="receiverable_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="sender_location_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_location_label", type="text", example="1"),
     *       @OA\Property(property="sender_area_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_area_label", type="text", example="1"),
     *       @OA\Property(property="sender_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_zone_label", type="text", example="1"),
     *       @OA\Property(property="receiver_location_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_location_label", type="text", example="1"),
     *       @OA\Property(property="receiver_area_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_area_label", type="text", example="1"),
     *       @OA\Property(property="receiver_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_zone_label", type="text", example="1"),
     *       @OA\Property(property="task_scheduled_date", type="datetime", example="1"),
     *       @OA\Property(property="task_scheduled_from_time", type="time", example="1"),
     *       @OA\Property(property="task_scheduled_to_time", type="time", example="1"),
     *       @OA\Property(property="task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="packages", type="longtext", example="1"),
     *       @OA\Property(property="customer_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_name", type="text", example="1"),
     *       @OA\Property(property="customer_golden_rule", type="text", example="1"),
     *       @OA\Property(property="customer_is_active", type="Integer", example="1"),
     *       @OA\Property(property="customer_account_manager_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_industry_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_name", type="text", example="1"),
     *       @OA\Property(property="piggy_bank_id", type="Integer", example="1"),
     *       @OA\Property(property="store_id", type="Integer", example="1"),
     *       @OA\Property(property="app_token_id", type="Integer", example="1"),
     *       @OA\Property(property="app_ref_id", type="Integer", example="1"),
     *       @OA\Property(property="fulfillment_id", type="Integer", example="1"),
     *       @OA\Property(property="created_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *       @OA\Property(property="updated_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *    )
     * )
     * )
     * )
     */

    public function store(Request $request)
    {
        $flatorder = Flatorder::create($request->all());
        return response()->json($flatorder, 201);
    }

    /**
     * @OA\Put  (
     * path="/api/flatorder/{id}",
     * summary="Edit one Flatorder by id",
     * description="update One Flatorder by id",
     * operationId="postOneFlatorders",
     * tags={"flatorder"},
     * @OA\Parameter(
     *    description="ID of flatorder",
     *    in="path",
     *    name="id",
     *    required=true,
     *    example="1",
     * ),
     * @OA\RequestBody(
     *    required=false,
     *    description="Flatorder fields",
     *    @OA\JsonContent(
     *       @OA\Property(property="id", type="Integer", example="1"),
     *       @OA\Property(property="order_number", type="text", example="1"),
     *       @OA\Property(property="waybill", type="text", example="1"),
     *       @OA\Property(property="parent_id", type="Integer", example="1"),
     *       @OA\Property(property="order_id", type="Integer", example="1"),
     *       @OA\Property(property="order_details_id", type="Integer", example="1"),
     *       @OA\Property(property="type_id", type="Integer", example="1"),
     *       @OA\Property(property="rate", type="Integer", example="1"),
     *       @OA\Property(property="status", type="Integer", example="1"),
     *       @OA\Property(property="payment_status", type="Integer", example="1"),
     *       @OA\Property(property="package_status", type="Integer", example="1"),
     *       @OA\Property(property="remaining_balance", type="decimal", example="1"),
     *       @OA\Property(property="price", type="decimal", example="1"),
     *       @OA\Property(property="payment_type_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="collection_amount", type="decimal", example="1"),
     *       @OA\Property(property="collection_type_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="comment_id", type="Integer", example="1"),
     *       @OA\Property(property="important_comment_text", type="text", example="1"),
     *       @OA\Property(property="comments_count", type="Integer", example="1"),
     *       @OA\Property(property="allow_receiver_contact", type="Integer", example="1"),
     *       @OA\Property(property="send_receiver_msg", type="Integer", example="1"),
     *       @OA\Property(property="car_needed", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_wakilni", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_customer", type="Integer", example="1"),
     *       @OA\Property(property="active", type="Integer", example="1"),
     *       @OA\Property(property="is_critical", type="Integer", example="1"),
     *       @OA\Property(property="require_signature", type="Integer", example="1"),
     *       @OA\Property(property="require_picture", type="Integer", example="1"),
     *       @OA\Property(property="same_package", type="Integer", example="1"),
     *       @OA\Property(property="piggy_bank_submission_id", type="Integer", example="1"),
     *       @OA\Property(property="completed_on", type="datetime", example="1"),
     *       @OA\Property(property="status_updated_at", type="datetime", example="1"),
     *       @OA\Property(property="become_critical_date", type="datetime", example="1"),
     *       @OA\Property(property="confirmed_at", type="datetime", example="1"),
     *       @OA\Property(property="note", type="text", example="1"),
     *       @OA\Property(property="preferred_sender_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_sender_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_sender_to_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_receiver_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_to_time", type="time", example="1"),
     *       @OA\Property(property="senderable_id", type="Integer", example="1"),
     *       @OA\Property(property="senderable_type", type="text", example="1"),
     *       @OA\Property(property="senderable_name", type="text", example="1"),
     *       @OA\Property(property="senderable_phone_number", type="text", example="1"),
     *       @OA\Property(property="senderable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_id", type="Integer", example="1"),
     *       @OA\Property(property="receiverable_type", type="text", example="1"),
     *       @OA\Property(property="receiverable_name", type="text", example="1"),
     *       @OA\Property(property="receiverable_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="sender_location_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_location_label", type="text", example="1"),
     *       @OA\Property(property="sender_area_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_area_label", type="text", example="1"),
     *       @OA\Property(property="sender_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_zone_label", type="text", example="1"),
     *       @OA\Property(property="receiver_location_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_location_label", type="text", example="1"),
     *       @OA\Property(property="receiver_area_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_area_label", type="text", example="1"),
     *       @OA\Property(property="receiver_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_zone_label", type="text", example="1"),
     *       @OA\Property(property="task_scheduled_date", type="datetime", example="1"),
     *       @OA\Property(property="task_scheduled_from_time", type="time", example="1"),
     *       @OA\Property(property="task_scheduled_to_time", type="time", example="1"),
     *       @OA\Property(property="task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="packages", type="longtext", example="1"),
     *       @OA\Property(property="customer_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_name", type="text", example="1"),
     *       @OA\Property(property="customer_golden_rule", type="text", example="1"),
     *       @OA\Property(property="customer_is_active", type="Integer", example="1"),
     *       @OA\Property(property="customer_account_manager_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_industry_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_name", type="text", example="1"),
     *       @OA\Property(property="piggy_bank_id", type="Integer", example="1"),
     *       @OA\Property(property="store_id", type="Integer", example="1"),
     *       @OA\Property(property="app_token_id", type="Integer", example="1"),
     *       @OA\Property(property="app_ref_id", type="Integer", example="1"),
     *       @OA\Property(property="fulfillment_id", type="Integer", example="1"),
     *    ),
     * ),
     * @OA\Response(
     *    response=200,
     *    description="Returns when Flatorder has been created",
     *    @OA\JsonContent(
     *     @OA\Items(
     *       @OA\Property(property="id", type="Integer", example="1"),
     *       @OA\Property(property="order_number", type="text", example="1"),
     *       @OA\Property(property="waybill", type="text", example="1"),
     *       @OA\Property(property="parent_id", type="Integer", example="1"),
     *       @OA\Property(property="order_id", type="Integer", example="1"),
     *       @OA\Property(property="order_details_id", type="Integer", example="1"),
     *       @OA\Property(property="type_id", type="Integer", example="1"),
     *       @OA\Property(property="rate", type="Integer", example="1"),
     *       @OA\Property(property="status", type="Integer", example="1"),
     *       @OA\Property(property="payment_status", type="Integer", example="1"),
     *       @OA\Property(property="package_status", type="Integer", example="1"),
     *       @OA\Property(property="remaining_balance", type="decimal", example="1"),
     *       @OA\Property(property="price", type="decimal", example="1"),
     *       @OA\Property(property="payment_type_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="collection_amount", type="decimal", example="1"),
     *       @OA\Property(property="collection_type_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="comment_id", type="Integer", example="1"),
     *       @OA\Property(property="important_comment_text", type="text", example="1"),
     *       @OA\Property(property="comments_count", type="Integer", example="1"),
     *       @OA\Property(property="allow_receiver_contact", type="Integer", example="1"),
     *       @OA\Property(property="send_receiver_msg", type="Integer", example="1"),
     *       @OA\Property(property="car_needed", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_wakilni", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_customer", type="Integer", example="1"),
     *       @OA\Property(property="active", type="Integer", example="1"),
     *       @OA\Property(property="is_critical", type="Integer", example="1"),
     *       @OA\Property(property="require_signature", type="Integer", example="1"),
     *       @OA\Property(property="require_picture", type="Integer", example="1"),
     *       @OA\Property(property="same_package", type="Integer", example="1"),
     *       @OA\Property(property="piggy_bank_submission_id", type="Integer", example="1"),
     *       @OA\Property(property="completed_on", type="datetime", example="1"),
     *       @OA\Property(property="status_updated_at", type="datetime", example="1"),
     *       @OA\Property(property="become_critical_date", type="datetime", example="1"),
     *       @OA\Property(property="confirmed_at", type="datetime", example="1"),
     *       @OA\Property(property="note", type="text", example="1"),
     *       @OA\Property(property="preferred_sender_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_sender_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_sender_to_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_receiver_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_to_time", type="time", example="1"),
     *       @OA\Property(property="senderable_id", type="Integer", example="1"),
     *       @OA\Property(property="senderable_type", type="text", example="1"),
     *       @OA\Property(property="senderable_name", type="text", example="1"),
     *       @OA\Property(property="senderable_phone_number", type="text", example="1"),
     *       @OA\Property(property="senderable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_id", type="Integer", example="1"),
     *       @OA\Property(property="receiverable_type", type="text", example="1"),
     *       @OA\Property(property="receiverable_name", type="text", example="1"),
     *       @OA\Property(property="receiverable_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="sender_location_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_location_label", type="text", example="1"),
     *       @OA\Property(property="sender_area_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_area_label", type="text", example="1"),
     *       @OA\Property(property="sender_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_zone_label", type="text", example="1"),
     *       @OA\Property(property="receiver_location_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_location_label", type="text", example="1"),
     *       @OA\Property(property="receiver_area_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_area_label", type="text", example="1"),
     *       @OA\Property(property="receiver_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_zone_label", type="text", example="1"),
     *       @OA\Property(property="task_scheduled_date", type="datetime", example="1"),
     *       @OA\Property(property="task_scheduled_from_time", type="time", example="1"),
     *       @OA\Property(property="task_scheduled_to_time", type="time", example="1"),
     *       @OA\Property(property="task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="packages", type="longtext", example="1"),
     *       @OA\Property(property="customer_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_name", type="text", example="1"),
     *       @OA\Property(property="customer_golden_rule", type="text", example="1"),
     *       @OA\Property(property="customer_is_active", type="Integer", example="1"),
     *       @OA\Property(property="customer_account_manager_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_industry_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_name", type="text", example="1"),
     *       @OA\Property(property="piggy_bank_id", type="Integer", example="1"),
     *       @OA\Property(property="store_id", type="Integer", example="1"),
     *       @OA\Property(property="app_token_id", type="Integer", example="1"),
     *       @OA\Property(property="app_ref_id", type="Integer", example="1"),
     *       @OA\Property(property="fulfillment_id", type="Integer", example="1"),
     *       @OA\Property(property="created_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *       @OA\Property(property="updated_at", type="string", example="2021-03-10T09:04:27.000000Z"),
     *    )
     * )
     * )
     * )
     */

    public function update(Request $request, Flatorder $flatorder)
    {
        $flatorder->update($request->all());

        return response()->json($flatorder, 200);
    }

    /**
     * @OA\Delete (
     * path="/api/flatorder/{id}",
     * summary="delete Flatorder by id",
     * description="delete one Flatorder by id",
     * operationId="deleteOneFlatorders",
     * tags={"flatorder"},
     * @OA\Parameter(
     *    description="ID of flatorder",
     *    in="path",
     *    name="id",
     *    required=true,
     *    example="1",
     * ),
     * @OA\Response(
     *    response=404,
     *    description="Returns when flatorder id is not found",
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="Resource not found"),
     *    )
     * ),
     * @OA\Response(
     *    response=200,
     *    description="Returns when Flatorders are found",
     *    @OA\JsonContent(
     *       @OA\Property(property="id", type="Integer", example="1"),
     *       @OA\Property(property="order_number", type="text", example="1"),
     *       @OA\Property(property="waybill", type="text", example="1"),
     *       @OA\Property(property="parent_id", type="Integer", example="1"),
     *       @OA\Property(property="order_id", type="Integer", example="1"),
     *       @OA\Property(property="order_details_id", type="Integer", example="1"),
     *       @OA\Property(property="type_id", type="Integer", example="1"),
     *       @OA\Property(property="rate", type="Integer", example="1"),
     *       @OA\Property(property="status", type="Integer", example="1"),
     *       @OA\Property(property="payment_status", type="Integer", example="1"),
     *       @OA\Property(property="package_status", type="Integer", example="1"),
     *       @OA\Property(property="remaining_balance", type="decimal", example="1"),
     *       @OA\Property(property="price", type="decimal", example="1"),
     *       @OA\Property(property="payment_type_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="price_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="collection_amount", type="decimal", example="1"),
     *       @OA\Property(property="collection_type_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_id", type="Integer", example="1"),
     *       @OA\Property(property="collection_currency_exchange_rate", type="double(8,2)", example="1"),
     *       @OA\Property(property="comment_id", type="Integer", example="1"),
     *       @OA\Property(property="important_comment_text", type="text", example="1"),
     *       @OA\Property(property="comments_count", type="Integer", example="1"),
     *       @OA\Property(property="allow_receiver_contact", type="Integer", example="1"),
     *       @OA\Property(property="send_receiver_msg", type="Integer", example="1"),
     *       @OA\Property(property="car_needed", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_wakilni", type="Integer", example="1"),
     *       @OA\Property(property="settled_with_customer", type="Integer", example="1"),
     *       @OA\Property(property="active", type="Integer", example="1"),
     *       @OA\Property(property="is_critical", type="Integer", example="1"),
     *       @OA\Property(property="require_signature", type="Integer", example="1"),
     *       @OA\Property(property="require_picture", type="Integer", example="1"),
     *       @OA\Property(property="same_package", type="Integer", example="1"),
     *       @OA\Property(property="piggy_bank_submission_id", type="Integer", example="1"),
     *       @OA\Property(property="completed_on", type="datetime", example="1"),
     *       @OA\Property(property="status_updated_at", type="datetime", example="1"),
     *       @OA\Property(property="become_critical_date", type="datetime", example="1"),
     *       @OA\Property(property="confirmed_at", type="datetime", example="1"),
     *       @OA\Property(property="note", type="text", example="1"),
     *       @OA\Property(property="preferred_sender_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_sender_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_sender_to_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_date", type="datetime", example="1"),
     *       @OA\Property(property="preferred_receiver_from_time", type="time", example="1"),
     *       @OA\Property(property="preferred_receiver_to_time", type="time", example="1"),
     *       @OA\Property(property="senderable_id", type="Integer", example="1"),
     *       @OA\Property(property="senderable_type", type="text", example="1"),
     *       @OA\Property(property="senderable_name", type="text", example="1"),
     *       @OA\Property(property="senderable_phone_number", type="text", example="1"),
     *       @OA\Property(property="senderable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_id", type="Integer", example="1"),
     *       @OA\Property(property="receiverable_type", type="text", example="1"),
     *       @OA\Property(property="receiverable_name", type="text", example="1"),
     *       @OA\Property(property="receiverable_phone_number", type="text", example="1"),
     *       @OA\Property(property="receiverable_secondary_phone_number", type="text", example="1"),
     *       @OA\Property(property="sender_location_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_location_label", type="text", example="1"),
     *       @OA\Property(property="sender_area_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_area_label", type="text", example="1"),
     *       @OA\Property(property="sender_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="sender_zone_label", type="text", example="1"),
     *       @OA\Property(property="receiver_location_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_location_label", type="text", example="1"),
     *       @OA\Property(property="receiver_area_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_area_label", type="text", example="1"),
     *       @OA\Property(property="receiver_zone_id", type="Integer", example="1"),
     *       @OA\Property(property="receiver_zone_label", type="text", example="1"),
     *       @OA\Property(property="task_scheduled_date", type="datetime", example="1"),
     *       @OA\Property(property="task_scheduled_from_time", type="time", example="1"),
     *       @OA\Property(property="task_scheduled_to_time", type="time", example="1"),
     *       @OA\Property(property="task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_contact_id", type="Integer", example="1"),
     *       @OA\Property(property="last_task_driver_user_name", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_phone_number", type="text", example="1"),
     *       @OA\Property(property="last_task_driver_user_is_active", type="Integer", example="1"),
     *       @OA\Property(property="packages", type="longtext", example="1"),
     *       @OA\Property(property="customer_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_name", type="text", example="1"),
     *       @OA\Property(property="customer_golden_rule", type="text", example="1"),
     *       @OA\Property(property="customer_is_active", type="Integer", example="1"),
     *       @OA\Property(property="customer_account_manager_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_industry_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_id", type="Integer", example="1"),
     *       @OA\Property(property="customer_user_name", type="text", example="1"),
     *       @OA\Property(property="piggy_bank_id", type="Integer", example="1"),
     *       @OA\Property(property="store_id", type="Integer", example="1"),
     *       @OA\Property(property="app_token_id", type="Integer", example="1"),
     *       @OA\Property(property="app_ref_id", type="Integer", example="1"),
     *       @OA\Property(property="fulfillment_id", type="Integer", example="1"),
     *       @OA\Property(property="deleted_at", type="string", example="2021-03-10T15:47:13.000000Z"),
     *       @OA\Property(property="created_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *       @OA\Property(property="updated_at", type="string", example="2021-03-10T09:03:27.000000Z"),
     *    )
     * )
     * )
     * )
     */
    public function delete(Flatorder $flatorder)
    {
        $flatorder->delete();

        return response()->json($flatorder, 200);
    }
}